name: VLE-5 DevOps CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t devops-lab-app:latest ./app

      - name: Start Minikube
        uses: medyagh/setup-minikube@latest

      - name: Load Docker Image into Minikube
        run: minikube image load devops-lab-app:latest

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/deployment.yml
          kubectl apply -f k8s/service.yml

      - name: Verify Deployment
        run: |
          kubectl get pods
          kubectl get deployments
          kubectl get services
